### ISSUE TITLE
incorrect URL for the role

### ISSUE THREAD

**Issue by beckej13820** [pressbooks/ansible-role-princexml#1]
Error message below, failed to download role from github.
---
- downloading role 'princexml', owned by pressbooks
- downloading role from https://github.com/pressbooks/ansible-role-princexml/archive/v1.1.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found

 [WARNING]: - pressbooks.princexml was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
----

I think the correct URL is https://github.com/pressbooks/ansible-role-princexml/archive/1.1.tar.gz and there is just an extra v

**Comment by greatislander** [comment]
Thanks for reporting this @beckej13820. I'd tagged that version incorrectly the first time which I think caused some issues. I've updated to 11.3 now (mapping to the version of Prince that the role installs by default) — this should fix your issue.
